version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: ./tg_bot/Dockerfile
    depends_on:
      - web
    volumes:
      - ./:/code:ro

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://vet_clinic_user:vet_clinic_pass@db/vet_clinic_db
    ports:
      - "5555:5555"

  db:
      image: postgres:14-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5432
      environment:
        - POSTGRES_USER=vet_clinic_user
        - POSTGRES_PASSWORD=vet_clinic_pass
        - POSTGRES_DB=vet_clinic_db
      healthcheck:
        test: pg_isready -U vet_clinic_user -d vet_clinic_db
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
      postgres_data:
